// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SimpQi_username_consistent', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SimpQi_username_consistent', async function() {
    // Test name: SimpQi_username_consistent
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")

    // 3 | click | css=.fluid |  | 
    await driver.findElement(By.css(".fluid")).click()
    // 4 | click | css=.fluid |  | 
    await driver.findElement(By.css(".fluid")).click()
    // 5 | click | css=.fluid |  | 
    await driver.findElement(By.css(".fluid")).click()
    // 6 | verifyText | css=.js-username | herbert | 
    assert(await driver.findElement(By.css(".js-username")).getText() == "herbert")
  })
})
